### ISSUE TITLE
Proxy mode - DA - concurrent map iteration and map write

### ISSUE THREAD

**Issue by gwandwingor** [Axway/agents-apigee#146] opened 2023-09-18 16:36 UTC
Hi,

We have an environment with almost 400 API proxies. 
After a few hours the DA has been up and running, the error below appears in the log and the agent becomes "unhealthy" until it is manually restarted.

![image](https://github.com/Axway/agents-apigee/assets/22820414/8a1e6e69-23fb-48ca-b348-adb1a497c720)

Full log available on demand

Can you please help understand what causes this concurrent access ?

DA v0.1.21

Thanks

**Comment by jcollins-axway** [comment] 2023-09-25 21:13
This seems to be an issue with the cache in the SDK, but the screenshot of the log does not give much to go on. Is there any more data that can be provided>

**Comment by jcollins-axway** [comment] 2023-09-25 22:27
I have found a place where a concurrent read/write could be happening to the map. It would only occur in the proxy mode, so this is likely the cause.

**Comment by jcollins-axway** [comment] 2023-09-25 22:29
Will be fixed when APIGOV-26363 is merged

**Closed** 2023-09-26 17:18 UTC
Labels: bug
